### PR TITLE
Adding the support for POWER ppc64le platform

### PR DESCRIPTION
**Pull request by bahetiamit**
Signed-off-by: Amit Baheti  <aramswar@in.ibm.com>

### CODE REVIEW

**Comment by ericwill** [comment]
Nice contribution, thanks. I'm going to convert this repo to use docker buildx like the [che-sidecar-openshift-connector](https://github.com/che-dockerfiles/che-sidecar-openshift-connector) repo does. Then I'll merge the PR.

**Comment by ericwill** [comment]
Okay I've configured this repository now. Can you make your PR against the master branch, and update it to be the same as your other [PR for the che-sidecar-openshift-connector](https://github.com/che-dockerfiles/che-sidecar-openshift-connector/pull/12) repo was?

**Comment by ghatwala** [comment]
Thanks @ericwill  for the guidance here :-) ...  guess using "buildx" to create cross compiled builds ( for non-x86 platoforms like `s390x, ppc64le , ARM`) is the new way [forward](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/blob/master/.github/workflows/build-publish.yaml#L35) . Using github actions  to create multi-arch builds to leverage `buildx` is great.

**Comment by bahetiamit** [comment]
@ericwill As suggested, I have raised a PR against master branch with the required changes - https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/pull/17

**Comment by ericwill** [comment]
> @ericwill As suggested, I have raised a PR against master branch with the required changes - #17

Merged that one, closing this one.

**Pull request closed without merging**
