### PR TITLE
Install minikube in the Kubernetes tooling sidecar

### LINKED ISSUE #17501: Kubernetes plugin wants `minikube` to be installed in the container
### Describe the bug

The latest Kubernetes plugin cannot be launched inside Che-Theia.

In the workspaces, created from [devfiles](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/tree/master/dogfooding), it's become not possible to develop K8S plugin cloned from it's repository.
The newer version of the plugin requires the `minikube` to be installed in the container.

### Che version

 - [x] latest
 - [x] nightly

### Steps to reproduce

1. Create workspace from the [devfile](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/blob/master/dogfooding/devfile.yaml)
2. Inject kubeconfig
3. Run 1.1, 1.2, 1.3 commands
4. Run 2.1 and 2.2 commands
5. Open Che-Theia dev instance and check Kubernetes plugin

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

Screenshot from 2020-07-28 13-40-40

Screenshot from 2020-07-28 13-41-08

### Installation method
   - [x] chectl

### Environment
   - [x] my computer
       - [x] Linux

### PR DESCRIPTION
**Pull request by ericwill**
Closes eclipse/che#17501

Signed-off-by: Eric Williams <ericwill@redhat.com>

### CODE REVIEW

**Review by vitaliy-guliy — APPROVED** [review]
I'm still continue receiving errors when trying to launch k8s extension. But now they are not related to minikube.

**Comment by ericwill** [comment]
> I'm still continue receiving errors when trying to launch k8s extension. But now they are not related to minikube.

Thanks for the review. Can you file an issue for the errors?

**Comment by vitaliy-guliy** [comment]
Yes, sure. But first, I will check it without your changes. Just to be sure that it's not depend on the container in which the plugin is running.

**Comment by vitaliy-guliy** [comment]
An issue describing the problem https://github.com/eclipse/che/issues/17609

**Pull request merged**
