### PR TITLE
Add vscode-kubernetes-tools 1.1.0 image

### PR DESCRIPTION
**Pull request by mkuznyetsov**
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
I really wish we were pushing these to master, then cutting a tag/branch for the new releases. Why make the change history impossible to see  as small changes in the same branch, like we have for all other che repos?

**Comment by vitaliy-guliy** [comment]
I also prefer to have this in master.

**Review by vitaliy-guliy — APPROVED** [review]

**Comment by vitaliy-guliy** [comment]
@benoitf could you review this PR?

**Comment by ericwill** [comment]
Florent is on PTO, I'll review it today.

> I really wish we were pushing these to master, then cutting a tag/branch for the new releases. Why make the change history impossible to see as small changes in the same branch, like we have for all other che repos?

I agree, there is a discussion ongoing in eclipse/che#15949 on the best way forward to change the layout of this repo.

**Review by ericwill — APPROVED** [review]
LGTM.

**Pull request merged**
