### PR TITLE
bump to newer deps - helm 3.0.3, kubectl 1.17.2, buildah 1.12.0

### PR DESCRIPTION
**Pull request by nickboldt**
bump to newer deps - helm 3.0.3, kubectl 1.17.2, buildah 1.12.0

Change-Id: I103505513c7ed7ef5df1d840fa7f531af2336bf7
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
Since the openshift connector is based on Fedora/builadh image, maybe we should move this one over to that same base too? Why have alpine here and Fedora there?

**Comment by nickboldt** [comment]
see related discussion in https://github.com/che-dockerfiles/che-sidecar-openshift-connector/pull/7

cc: @mkuznyetsov

**Comment by ericwill** [comment]
@nickboldt do you generally go around bumping these dependencies yourself (manually)? If so then I think we should introduce some automation here (a la dependabot, or something similar).

**Comment by nickboldt** [comment]
Yes, it's manual. 

And yes, we need better automated orchestration, like dependabot.

But mostly we need the upstream producers of the vsix files to support a wider range of cli binaries. AFAIU today the vsix will try to install odo 1.0.1 even if you already have 1.0.2 in your container. 

We need input from the adapters team, eg., @dgolovin.

**Review by ericwill — CHANGES_REQUESTED** [review]
LGTM. I checked and it doesn't seem like the Kubernetes extension downloads any dependencies automatically. Sounds like something that is specific to the OpenShift connector plug-in?

**Review by ericwill — APPROVED** [review]

**Comment by ericwill** [comment]
Derp, the "DO NOT MERGE" thing isn't in the commit message, my bad. I am still getting used to GitHub.

**Pull request merged**
